version: "3.9"
services:
  webserver:
    image: nginx:latest
    networks:
      - app
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    networks:
      - app
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  fingerprint-api:
    build: ./api/
    networks:
      - app
    restart: always
    volumes:
      - ./output:/app/output
  packet-sniffer:
    build: ./packet-sniffer/
    network_mode: service:webserver
    restart: always
  redis:
    image: redis:latest
    networks:
      - app
    restart: always
networks:
  app:
    name: fingerprint_app_network